apiVersion: v1
kind: Namespace
metadata:
  name: hello-world

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - image: hemashree3016/helloworld8081:v1
        name: my-container
        ports:
        - containerPort: 80  # Specify the port your application listens on

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    app: hello-world
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer  # Expose the service as a LoadBalancer
